name: Waka Readme

on:
  schedule:
    - cron: '50 02 * * *'  # 9:50 PM Colombia = 2:50 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "es"
          SHOW_OS: "false"
          SHOW_PROJECTS: "false"
          SHOW_EDITORS: "false"
          SHOW_LANGUAGE: "true"
          SHOW_LINES_OF_CODE: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_COMMIT: "false"
          SHOW_UPDATED_DATE: "false"
          SHOW_TOTAL_CODE_TIME: "false"
